### ISSUE TITLE
monthly HLW model estimate of US data not work well

### ISSUE THREAD

**Issue by shubingtang** [davidakelley/MFSS#3]
Hi,
I tried to use MFSS to handle  [HLW model](https://www.frbsf.org/economic-research/files/wp2016-11.pdf),and I set c=1 according to HLW model.

But the result of HLW estimate of the natural rate of interest of US at the monthly frequency is very poor.Is there a problem in my code?
[US_HLW_MFSS.zip](https://github.com/davidakelley/MFSS/files/5746539/US_HLW_MFSS.zip)

And if I need the estimation of the model parameters,what should I do?

Thank you for any help in advance.

**Comment by davidakelley** [comment]
I don't have the bandwidth right now to help debug your code (nor do I think I can because it looks like the data you're using are different than the LW example in the package and I don't have your data), but I think your approach is correct. I would recommend you look at whether any of the estimated parameters are hitting bounds that are being set in the code - the bounds that we set in the examples were really there to help the estimation along and I don't think they should be binding. If they are, relax them and see if the estimates look more reasonable, and check whether they make intuitive sense. 

As for what to do about getting the estimated model parameters, it looks like your code is already getting them as `thetaMOpt` and `thetaOptQ`. If you need the names of the parameters, try looking at `ssEQ.ThetaMapping.thetaNames`.
