### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by sajamac** [davidakelley/MFSS#5]
I am having some difficulty installing the package. I download the zip file and extracted the files into c:\project\MFSS directory.
Then I ran make_toolbox.m file by typing "make_toolbox(2,8,0)" on the command line to create MFSS.mltbx file.
But I got  the following error messages:

Error using matlab.addons.toolbox.packageToolbox (line 89)
Unable to package the project 'P:\project\nowcasting\codes\MFSS\toolbox.prj'. Toolbox root MFSS does not exist.

Error in make_toolbox (line 33)
matlab.addons.toolbox.packageToolbox(...

What did I do wrong here?

**Comment by davidakelley** [comment]
So sorry for the delay in addressing this...

I don't think you should need `make_toolbox` in order to install the package. You should be able to simply add the main directory and the `src` directory and be able to call the functions you need. 

However, the much easier way to use this is to download the `.mltbx` file from the [Releases](https://github.com/davidakelley/MFSS/releases/tag/2.8.0) page. You should then be able to double click on that and Matlab will install it so that you don't have to worry about the paths anymore.
